version: '3.9'

services:
#  front:
#    image: sermalenk/skypro-front:version_1
#    ports:
#      - 80:80
#    depends_on:
#      - api
#  api:
#    build:
#      context: .
#    image: armenar/diploma_app:tagname
#    depends_on:
#      postgres:
#        condition: service_healthy
#      migrations:
#        condition: service_completed_successfully
#    volumes:
#      - ./.docker_env:/app/.env
#  migrations:
#    build:
#      context: .
#    image: armenar/diploma_app:tagname
#    depends_on:
#      postgres:
#        condition: service_healthy
#    volumes:
#      - ./.docker_env:/app/.env
#    command: python manage.py migrate
#  postgres:
  main_todolist_db:
    image: postgres:12.0-alpine
    volumes:
      - todolist_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=todolist
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432

#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

volumes:
  todolist_postgres_data:
