name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs_on: ubuntu_latest
    steps:
      - name: clone cod
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t armenar/diploma_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .


#      - name: docker login
#          run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#      - name: docker push
#description:
#runs:#          run: docker push armenar/insta:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
