name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t armenar/diploma_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
